### ISSUE TITLE
rmdir should produce error 'ENOTEMPTY' when a directory is not empty

### ISSUE THREAD

**Issue by kdvolder** [eldargab/node-fake-fs#3]
Right now I think it deletes the directory without producing an error.

**Comment by kdvolder** [comment]
Please ignore previous fix attempt which didn't work. The pull request #4 does work. It is indirectly tested by some tests in our own codebase which use fake-fs, but I did not add any regression tests to fake-fs itself.

**Comment by eldargab** [comment]
Thanks for reporting.

**Comment by kdvolder** [comment]
Thanks for fixing it so quickly, and thanks for fakefs in general. It is a very useful testing tool :-)
